### ISSUE TITLE
Abyss is in German

### ISSUE THREAD

**Issue by oHeckGage** [AstralService/Abyss#1]
Google on Abyss is in german.
![image](https://user-images.githubusercontent.com/68713542/187045875-cbfb172b-1e80-4660-8b57-e74df744c97f.png)
Also, it doesn't mention how to search anywhere and is extremely vague.
Is there a way to search or is it just simply you click enter after clicking search and you go to Google? You should add a typing feature into the Search bar.

**Comment by oHeckGage** [comment]
Also, idk if this is because your VPS is located in Germany, and if that is, it'll probably fix yourself after VPS upgrade.

**Comment by pyroTM** [comment]
it is because its hosted in germany it will be fixed once we migrate to a vps in America which will happen on September 1st

**Comment by pyroTM** [comment]
Click the bottom right button thats blue and it should redirect to normal google
